-- SQL Analytical Query #1 — Daily Wave Summary

SELECT
    TO_DATE(TIMESTAMP) AS DAY,
    AVG(WAVE_HEIGHT) AS AVG_WAVE_HEIGHT,
    MAX(WAVE_HEIGHT) AS MAX_WAVE_HEIGHT,
    AVG(WIND_SPEED) AS AVG_WIND_SPEED,
    AVG(SWELL_HEIGHT) AS AVG_SWELL_HEIGHT
FROM STORM_MARINE_CLEAN
GROUP BY DAY
ORDER BY DAY DESC;


-- SQL Analytical Query #2 — Dangerous Wave Detection

SELECT
    COUNT(*) AS DANGEROUS_WAVE_COUNT,
    MIN(WAVE_HEIGHT) AS MIN_DANGER,
    MAX(WAVE_HEIGHT) AS MAX_DANGER,
    AVG(WAVE_HEIGHT) AS AVG_DANGER,
    TO_DATE(TIMESTAMP) AS DAY
FROM STORM_MARINE_CLEAN
WHERE WAVE_HEIGHT > 6.0
GROUP BY DAY
ORDER BY DAY DESC;


-- SQL Analytical Query #3 — Correlation Analysis

SELECT
    CORR(WAVE_HEIGHT, WIND_SPEED) AS CORR_WAVE_WIND,
    CORR(WAVE_HEIGHT, SWELL_HEIGHT) AS CORR_WAVE_SWELL
FROM STORM_MARINE_CLEAN;